version: '3.8'

services:
  # 1. База данных PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: learning-postgres
    environment:
      POSTGRES_USER: learning_admin
      POSTGRES_PASSWORD: "MesaSuperPassword2026!"
      POSTGRES_DB: learning_platform_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  # 2. Твое Next.js приложение
  nextjs-app:
    build: .
    container_name: learning-platform-app
    ports:
      - "80:3000"
    environment:
      DATABASE_URL: "postgresql://learning_admin:MesaSuperPassword2026!@postgres-db:5432/learning_platform_db?schema=public"
      SESSION_SECRET: "super-secret-padlock-key-for-iron-session-32"
      HOST: "0.0.0.0"
      PORT: 3000
      # НАСТРОЙКА ЛОГИРОВАНИЯ: Принудительный вывод ошибок трейса Node.js в консоль Docker
      NODE_OPTIONS: "--trace-warnings --expose-gc"
    # Настройка лог-драйвера, чтобы Docker сразу сбрасывал текст в буфер Linux
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    depends_on:
      - postgres-db

volumes:
  pg_data:
