name: Deploy Learning Platform

on:
  push:
    branches: [ main ] # Робот сработает, когда ты сделаешь push в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Cloud.ru via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: admin  # Твой проверенный юзер на сервере!
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p ~/learning-platform
          cd ~/learning-platform
          
          if [ ! -d ".git" ]; then
            git clone https://github.com{{ github.repository }}.git .
          else
            git pull origin main
          fi
          
          # Безопасно пишем секреты в файл .env прямо на сервере
          echo "DB_PASSWORD=${{ secrets.PRODUCTION_DB_PASSWORD }}" > .env
          echo "SESSION_SECRET=${{ secrets.PRODUCTION_SESSION_SECRET }}" >> .env
          
          # Пересобираем и запускаем контейнеры
          sudo docker compose up -d --build
